version: '3.8'
services:
  user-service:
    container_name: user-service
    hostname: user-service
    build:
      context: .
      dockerfile: Dockerfile
    image: sing3demons/user-service
    ports:
      - '8000:3000'
    environment:
      - DATABASE_URL=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/mydatabase?replicaSet=my-replica-set
      - KAFKA_BROKERS=kafka:9092
      - ACCESS_TOKEN_SECRET="secret"
      - REFRESH_TOKEN_SECRET="secret"
    networks:
      - ms-service
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
networks:
  ms-service:
   name: ms-service
   external: true