@url = http://localhost:8000/api

POST {{url}}/auth/register HTTP/1.1
Content-Type: application/json
Content-Length: 71

{
    "email": "sing5@dev.com",
    "password": "12345678",
    "username": "sing"
}

###
# @name auth
POST {{url}}/auth/sign-in HTTP/1.1
Content-Type: application/json
Content-Length: 71

{
    "email": "sing@dev.com",
    "password": "12345678"
}

### Get Token ###
@token = {{auth.response.body.$.data.$.access_token}}

###
GET {{url}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{url}}/users/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE  {{url}}/users/64bd2ce6495e23f11400628f HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/messenger/get-friends HTTP/1.1
Content-Type: application/json