version: "3.9"

services:
  loki:
    image: grafana/loki:2.8.4
    container_name: loki
    expose:
      - "3100"
    networks:
      - ms-service
  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      # - ./grafana-storage:/var/lib/grafana
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - ms-service
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"
    networks:
      - ms-service
networks:
  ms-service:
   name: ms-service

# Loki = http://loki:3100 

# dashboards -> 16306
# https://grafana.com/grafana/dashboards/16306-express-prometheus-middleware/