version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.46.0
    volumes:
       - ./:/etc/prometheus/
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - ms-service
networks:
  ms-service:
   name: ms-service
   external: true